name: cheatbusters
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  dio: ^5.3.3
  provider: ^6.1.1
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/splash_background.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#3A4A63" # yedek arka plan rengi
  background_image: assets/splash_background.png
  android_12:
    image: assets/logo.png
    icon_background_color: "#3A4A63"
